// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hours.sql

package dbmodels

import (
	"context"
	"time"

	"workout/trainer/domain"
)

const getHour = `-- name: GetHour :one
SELECT hour, availability FROM trainer.hours 
WHERE hour = $1
`

func (q *Queries) GetHour(ctx context.Context, hour time.Time) (TrainerHour, error) {
	row := q.db.QueryRow(ctx, getHour, hour)
	var i TrainerHour
	err := row.Scan(&i.Hour, &i.Availability)
	return i, err
}

const upsertHour = `-- name: UpsertHour :exec
INSERT INTO trainer.hours (hour, availability)
VALUES ($1, $2)
ON CONFLICT (hour) DO UPDATE
    SET availability = EXCLUDED.availability
`

type UpsertHourParams struct {
	Hour         time.Time
	Availability domain.Availability
}

func (q *Queries) UpsertHour(ctx context.Context, arg UpsertHourParams) error {
	_, err := q.db.Exec(ctx, upsertHour, arg.Hour, arg.Availability)
	return err
}
