// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbmodels

import (
	"database/sql/driver"
	"fmt"
	"time"

	"workout/trainer/domain"
)

type TrainerAvailability string

const (
	TrainerAvailabilityAvailable         TrainerAvailability = "available"
	TrainerAvailabilityNotAvailable      TrainerAvailability = "not_available"
	TrainerAvailabilityTrainingScheduled TrainerAvailability = "training_scheduled"
)

func (e *TrainerAvailability) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TrainerAvailability(s)
	case string:
		*e = TrainerAvailability(s)
	default:
		return fmt.Errorf("unsupported scan type for TrainerAvailability: %T", src)
	}
	return nil
}

type NullTrainerAvailability struct {
	TrainerAvailability TrainerAvailability
	Valid               bool // Valid is true if TrainerAvailability is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTrainerAvailability) Scan(value interface{}) error {
	if value == nil {
		ns.TrainerAvailability, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TrainerAvailability.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTrainerAvailability) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TrainerAvailability), nil
}

type TrainerHour struct {
	Hour         time.Time
	Availability domain.Availability
}
