// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbmodels

import (
	"workout/user/app/models"
)

type UserUser struct {
	UserUuid    models.UserUUID
	FirebaseUid string
	Username    string
	Role        models.Role
	Balance     int32
}
