// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package dbmodels

import (
	"context"

	"workout/user/app/models"
)

const createUser = `-- name: CreateUser :one
INSERT INTO "user".users (
    user_uuid,
    firebase_uid,
    username,
    role,
    balance
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING user_uuid, firebase_uid, username, role, balance
`

type CreateUserParams struct {
	UserUuid    models.UserUUID
	FirebaseUid string
	Username    string
	Role        models.Role
	Balance     int32
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (UserUser, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.UserUuid,
		arg.FirebaseUid,
		arg.Username,
		arg.Role,
		arg.Balance,
	)
	var i UserUser
	err := row.Scan(
		&i.UserUuid,
		&i.FirebaseUid,
		&i.Username,
		&i.Role,
		&i.Balance,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT user_uuid, firebase_uid, username, role, balance
FROM "user".users
WHERE user_uuid = $1
`

func (q *Queries) GetUser(ctx context.Context, userUuid models.UserUUID) (UserUser, error) {
	row := q.db.QueryRow(ctx, getUser, userUuid)
	var i UserUser
	err := row.Scan(
		&i.UserUuid,
		&i.FirebaseUid,
		&i.Username,
		&i.Role,
		&i.Balance,
	)
	return i, err
}

const getUserBalance = `-- name: GetUserBalance :one
SELECT balance
FROM "user".users
WHERE firebase_uid = $1
`

func (q *Queries) GetUserBalance(ctx context.Context, firebaseUid string) (int32, error) {
	row := q.db.QueryRow(ctx, getUserBalance, firebaseUid)
	var balance int32
	err := row.Scan(&balance)
	return balance, err
}

const getUserByFirebaseUID = `-- name: GetUserByFirebaseUID :one
SELECT user_uuid, firebase_uid, username, role, balance
FROM "user".users
WHERE firebase_uid = $1
`

func (q *Queries) GetUserByFirebaseUID(ctx context.Context, firebaseUid string) (UserUser, error) {
	row := q.db.QueryRow(ctx, getUserByFirebaseUID, firebaseUid)
	var i UserUser
	err := row.Scan(
		&i.UserUuid,
		&i.FirebaseUid,
		&i.Username,
		&i.Role,
		&i.Balance,
	)
	return i, err
}

const updateBalance = `-- name: UpdateBalance :exec
UPDATE "user".users
SET balance = $2
WHERE firebase_uid = $1
`

type UpdateBalanceParams struct {
	FirebaseUid string
	Balance     int32
}

func (q *Queries) UpdateBalance(ctx context.Context, arg UpdateBalanceParams) error {
	_, err := q.db.Exec(ctx, updateBalance, arg.FirebaseUid, arg.Balance)
	return err
}
