// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbmodels

import (
	"time"

	"workout/training/domain"
)

type TrainingTraining struct {
	TrainingUuid   domain.TrainingUUID
	UserID         domain.UserID
	Username       string
	Time           time.Time
	Notes          *string
	ProposedTime   *time.Time
	MoveProposedBy *domain.UserType
	Canceled       bool
}
