// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trainings.sql

package dbmodels

import (
	"context"
	"time"

	"workout/training/domain"
)

const createTraining = `-- name: CreateTraining :exec
INSERT INTO training.trainings (
    training_uuid,
    user_id,
    username,
    time,
    notes,
    canceled
) VALUES (
    $1, $2, $3, $4, $5, $6
)
`

type CreateTrainingParams struct {
	TrainingUuid domain.TrainingUUID
	UserID       domain.UserID
	Username     string
	Time         time.Time
	Notes        *string
	Canceled     bool
}

func (q *Queries) CreateTraining(ctx context.Context, arg CreateTrainingParams) error {
	_, err := q.db.Exec(ctx, createTraining,
		arg.TrainingUuid,
		arg.UserID,
		arg.Username,
		arg.Time,
		arg.Notes,
		arg.Canceled,
	)
	return err
}

const findTrainingsForUser = `-- name: FindTrainingsForUser :many
SELECT training_uuid, user_id, username, time, notes, proposed_time, move_proposed_by, canceled
FROM training.trainings
WHERE user_id = $1 AND canceled = false
ORDER BY time ASC
`

func (q *Queries) FindTrainingsForUser(ctx context.Context, userID domain.UserID) ([]TrainingTraining, error) {
	rows, err := q.db.Query(ctx, findTrainingsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrainingTraining{}
	for rows.Next() {
		var i TrainingTraining
		if err := rows.Scan(
			&i.TrainingUuid,
			&i.UserID,
			&i.Username,
			&i.Time,
			&i.Notes,
			&i.ProposedTime,
			&i.MoveProposedBy,
			&i.Canceled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTraining = `-- name: GetTraining :one
SELECT training_uuid, user_id, username, time, notes, proposed_time, move_proposed_by, canceled
FROM training.trainings
WHERE training_uuid = $1
`

func (q *Queries) GetTraining(ctx context.Context, trainingUuid domain.TrainingUUID) (TrainingTraining, error) {
	row := q.db.QueryRow(ctx, getTraining, trainingUuid)
	var i TrainingTraining
	err := row.Scan(
		&i.TrainingUuid,
		&i.UserID,
		&i.Username,
		&i.Time,
		&i.Notes,
		&i.ProposedTime,
		&i.MoveProposedBy,
		&i.Canceled,
	)
	return i, err
}

const listAllTrainings = `-- name: ListAllTrainings :many
SELECT training_uuid, user_id, username, time, notes, proposed_time, move_proposed_by, canceled
FROM training.trainings
WHERE canceled = false
ORDER BY time ASC
`

func (q *Queries) ListAllTrainings(ctx context.Context) ([]TrainingTraining, error) {
	rows, err := q.db.Query(ctx, listAllTrainings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrainingTraining{}
	for rows.Next() {
		var i TrainingTraining
		if err := rows.Scan(
			&i.TrainingUuid,
			&i.UserID,
			&i.Username,
			&i.Time,
			&i.Notes,
			&i.ProposedTime,
			&i.MoveProposedBy,
			&i.Canceled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTraining = `-- name: UpdateTraining :exec
UPDATE training.trainings
SET
    time = $2,
    notes = $3,
    proposed_time = $4,
    move_proposed_by = $5,
    canceled = $6
WHERE training_uuid = $1
`

type UpdateTrainingParams struct {
	TrainingUuid   domain.TrainingUUID
	Time           time.Time
	Notes          *string
	ProposedTime   *time.Time
	MoveProposedBy *domain.UserType
	Canceled       bool
}

func (q *Queries) UpdateTraining(ctx context.Context, arg UpdateTrainingParams) error {
	_, err := q.db.Exec(ctx, updateTraining,
		arg.TrainingUuid,
		arg.Time,
		arg.Notes,
		arg.ProposedTime,
		arg.MoveProposedBy,
		arg.Canceled,
	)
	return err
}
