// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"workout/training/domain"

	"github.com/oapi-codegen/runtime"
)

// ErrorDetails defines model for ErrorDetails.
type ErrorDetails struct {
	EntityId   *string `json:"entity_id,omitempty"`
	EntityType *string `json:"entity_type,omitempty"`
	ErrorSlug  string  `json:"error_slug"`
	Message    string  `json:"message"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Details Detailed error information
	Details *[]ErrorDetails `json:"details,omitempty"`

	// Message Human-readable error message
	Message string `json:"message"`

	// Slug Error slug
	Slug string `json:"slug"`
}

// PostTraining defines model for PostTraining.
type PostTraining struct {
	Notes string    `json:"notes"`
	Time  time.Time `json:"time"`
}

// Training defines model for Training.
type Training struct {
	CanBeCancelled     bool                `json:"canBeCancelled"`
	MoveProposedBy     *domain.UserType    `json:"moveProposedBy,omitempty"`
	MoveRequiresAccept bool                `json:"moveRequiresAccept"`
	Notes              string              `json:"notes"`
	ProposedTime       *time.Time          `json:"proposedTime,omitempty"`
	Time               time.Time           `json:"time"`
	User               string              `json:"user"`
	UserUuid           domain.UserUUID     `json:"userUuid"`
	Uuid               domain.TrainingUUID `json:"uuid"`
}

// Trainings defines model for Trainings.
type Trainings struct {
	Trainings []Training `json:"trainings"`
}

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// CreateTrainingJSONRequestBody defines body for CreateTraining for application/json ContentType.
type CreateTrainingJSONRequestBody = PostTraining

// RequestRescheduleTrainingJSONRequestBody defines body for RequestRescheduleTraining for application/json ContentType.
type RequestRescheduleTrainingJSONRequestBody = PostTraining

// RescheduleTrainingJSONRequestBody defines body for RescheduleTraining for application/json ContentType.
type RescheduleTrainingJSONRequestBody = PostTraining

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetTrainings request
	GetTrainings(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateTrainingWithBody request with any body
	CreateTrainingWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateTraining(ctx context.Context, body CreateTrainingJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CancelTraining request
	CancelTraining(ctx context.Context, trainingUUID domain.TrainingUUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ApproveRescheduleTraining request
	ApproveRescheduleTraining(ctx context.Context, trainingUUID domain.TrainingUUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RejectRescheduleTraining request
	RejectRescheduleTraining(ctx context.Context, trainingUUID domain.TrainingUUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RequestRescheduleTrainingWithBody request with any body
	RequestRescheduleTrainingWithBody(ctx context.Context, trainingUUID domain.TrainingUUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	RequestRescheduleTraining(ctx context.Context, trainingUUID domain.TrainingUUID, body RequestRescheduleTrainingJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RescheduleTrainingWithBody request with any body
	RescheduleTrainingWithBody(ctx context.Context, trainingUUID domain.TrainingUUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	RescheduleTraining(ctx context.Context, trainingUUID domain.TrainingUUID, body RescheduleTrainingJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetTrainings(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetTrainingsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateTrainingWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateTrainingRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateTraining(ctx context.Context, body CreateTrainingJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateTrainingRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CancelTraining(ctx context.Context, trainingUUID domain.TrainingUUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCancelTrainingRequest(c.Server, trainingUUID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ApproveRescheduleTraining(ctx context.Context, trainingUUID domain.TrainingUUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewApproveRescheduleTrainingRequest(c.Server, trainingUUID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RejectRescheduleTraining(ctx context.Context, trainingUUID domain.TrainingUUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRejectRescheduleTrainingRequest(c.Server, trainingUUID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RequestRescheduleTrainingWithBody(ctx context.Context, trainingUUID domain.TrainingUUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRequestRescheduleTrainingRequestWithBody(c.Server, trainingUUID, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RequestRescheduleTraining(ctx context.Context, trainingUUID domain.TrainingUUID, body RequestRescheduleTrainingJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRequestRescheduleTrainingRequest(c.Server, trainingUUID, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RescheduleTrainingWithBody(ctx context.Context, trainingUUID domain.TrainingUUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRescheduleTrainingRequestWithBody(c.Server, trainingUUID, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RescheduleTraining(ctx context.Context, trainingUUID domain.TrainingUUID, body RescheduleTrainingJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRescheduleTrainingRequest(c.Server, trainingUUID, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetTrainingsRequest generates requests for GetTrainings
func NewGetTrainingsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/trainings")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateTrainingRequest calls the generic CreateTraining builder with application/json body
func NewCreateTrainingRequest(server string, body CreateTrainingJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateTrainingRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateTrainingRequestWithBody generates requests for CreateTraining with any type of body
func NewCreateTrainingRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/trainings")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCancelTrainingRequest generates requests for CancelTraining
func NewCancelTrainingRequest(server string, trainingUUID domain.TrainingUUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "trainingUUID", trainingUUID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/trainings/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewApproveRescheduleTrainingRequest generates requests for ApproveRescheduleTraining
func NewApproveRescheduleTrainingRequest(server string, trainingUUID domain.TrainingUUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "trainingUUID", trainingUUID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/trainings/%s/approve-reschedule", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRejectRescheduleTrainingRequest generates requests for RejectRescheduleTraining
func NewRejectRescheduleTrainingRequest(server string, trainingUUID domain.TrainingUUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "trainingUUID", trainingUUID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/trainings/%s/reject-reschedule", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRequestRescheduleTrainingRequest calls the generic RequestRescheduleTraining builder with application/json body
func NewRequestRescheduleTrainingRequest(server string, trainingUUID domain.TrainingUUID, body RequestRescheduleTrainingJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRequestRescheduleTrainingRequestWithBody(server, trainingUUID, "application/json", bodyReader)
}

// NewRequestRescheduleTrainingRequestWithBody generates requests for RequestRescheduleTraining with any type of body
func NewRequestRescheduleTrainingRequestWithBody(server string, trainingUUID domain.TrainingUUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "trainingUUID", trainingUUID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/trainings/%s/request-reschedule", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewRescheduleTrainingRequest calls the generic RescheduleTraining builder with application/json body
func NewRescheduleTrainingRequest(server string, trainingUUID domain.TrainingUUID, body RescheduleTrainingJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRescheduleTrainingRequestWithBody(server, trainingUUID, "application/json", bodyReader)
}

// NewRescheduleTrainingRequestWithBody generates requests for RescheduleTraining with any type of body
func NewRescheduleTrainingRequestWithBody(server string, trainingUUID domain.TrainingUUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "trainingUUID", trainingUUID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/trainings/%s/reschedule", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetTrainingsWithResponse request
	GetTrainingsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetTrainingsClientResponse, error)

	// CreateTrainingWithBodyWithResponse request with any body
	CreateTrainingWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateTrainingClientResponse, error)

	CreateTrainingWithResponse(ctx context.Context, body CreateTrainingJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateTrainingClientResponse, error)

	// CancelTrainingWithResponse request
	CancelTrainingWithResponse(ctx context.Context, trainingUUID domain.TrainingUUID, reqEditors ...RequestEditorFn) (*CancelTrainingClientResponse, error)

	// ApproveRescheduleTrainingWithResponse request
	ApproveRescheduleTrainingWithResponse(ctx context.Context, trainingUUID domain.TrainingUUID, reqEditors ...RequestEditorFn) (*ApproveRescheduleTrainingClientResponse, error)

	// RejectRescheduleTrainingWithResponse request
	RejectRescheduleTrainingWithResponse(ctx context.Context, trainingUUID domain.TrainingUUID, reqEditors ...RequestEditorFn) (*RejectRescheduleTrainingClientResponse, error)

	// RequestRescheduleTrainingWithBodyWithResponse request with any body
	RequestRescheduleTrainingWithBodyWithResponse(ctx context.Context, trainingUUID domain.TrainingUUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RequestRescheduleTrainingClientResponse, error)

	RequestRescheduleTrainingWithResponse(ctx context.Context, trainingUUID domain.TrainingUUID, body RequestRescheduleTrainingJSONRequestBody, reqEditors ...RequestEditorFn) (*RequestRescheduleTrainingClientResponse, error)

	// RescheduleTrainingWithBodyWithResponse request with any body
	RescheduleTrainingWithBodyWithResponse(ctx context.Context, trainingUUID domain.TrainingUUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RescheduleTrainingClientResponse, error)

	RescheduleTrainingWithResponse(ctx context.Context, trainingUUID domain.TrainingUUID, body RescheduleTrainingJSONRequestBody, reqEditors ...RequestEditorFn) (*RescheduleTrainingClientResponse, error)
}

type GetTrainingsClientResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Trainings
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetTrainingsClientResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetTrainingsClientResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetTrainingsClientResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CreateTrainingClientResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r CreateTrainingClientResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateTrainingClientResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateTrainingClientResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CancelTrainingClientResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r CancelTrainingClientResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CancelTrainingClientResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CancelTrainingClientResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ApproveRescheduleTrainingClientResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r ApproveRescheduleTrainingClientResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ApproveRescheduleTrainingClientResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ApproveRescheduleTrainingClientResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type RejectRescheduleTrainingClientResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r RejectRescheduleTrainingClientResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RejectRescheduleTrainingClientResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r RejectRescheduleTrainingClientResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type RequestRescheduleTrainingClientResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r RequestRescheduleTrainingClientResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RequestRescheduleTrainingClientResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r RequestRescheduleTrainingClientResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type RescheduleTrainingClientResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r RescheduleTrainingClientResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RescheduleTrainingClientResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r RescheduleTrainingClientResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetTrainingsWithResponse request returning *GetTrainingsClientResponse
func (c *ClientWithResponses) GetTrainingsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetTrainingsClientResponse, error) {
	rsp, err := c.GetTrainings(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetTrainingsClientResponse(rsp)
}

// CreateTrainingWithBodyWithResponse request with arbitrary body returning *CreateTrainingClientResponse
func (c *ClientWithResponses) CreateTrainingWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateTrainingClientResponse, error) {
	rsp, err := c.CreateTrainingWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateTrainingClientResponse(rsp)
}

func (c *ClientWithResponses) CreateTrainingWithResponse(ctx context.Context, body CreateTrainingJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateTrainingClientResponse, error) {
	rsp, err := c.CreateTraining(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateTrainingClientResponse(rsp)
}

// CancelTrainingWithResponse request returning *CancelTrainingClientResponse
func (c *ClientWithResponses) CancelTrainingWithResponse(ctx context.Context, trainingUUID domain.TrainingUUID, reqEditors ...RequestEditorFn) (*CancelTrainingClientResponse, error) {
	rsp, err := c.CancelTraining(ctx, trainingUUID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCancelTrainingClientResponse(rsp)
}

// ApproveRescheduleTrainingWithResponse request returning *ApproveRescheduleTrainingClientResponse
func (c *ClientWithResponses) ApproveRescheduleTrainingWithResponse(ctx context.Context, trainingUUID domain.TrainingUUID, reqEditors ...RequestEditorFn) (*ApproveRescheduleTrainingClientResponse, error) {
	rsp, err := c.ApproveRescheduleTraining(ctx, trainingUUID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseApproveRescheduleTrainingClientResponse(rsp)
}

// RejectRescheduleTrainingWithResponse request returning *RejectRescheduleTrainingClientResponse
func (c *ClientWithResponses) RejectRescheduleTrainingWithResponse(ctx context.Context, trainingUUID domain.TrainingUUID, reqEditors ...RequestEditorFn) (*RejectRescheduleTrainingClientResponse, error) {
	rsp, err := c.RejectRescheduleTraining(ctx, trainingUUID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRejectRescheduleTrainingClientResponse(rsp)
}

// RequestRescheduleTrainingWithBodyWithResponse request with arbitrary body returning *RequestRescheduleTrainingClientResponse
func (c *ClientWithResponses) RequestRescheduleTrainingWithBodyWithResponse(ctx context.Context, trainingUUID domain.TrainingUUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RequestRescheduleTrainingClientResponse, error) {
	rsp, err := c.RequestRescheduleTrainingWithBody(ctx, trainingUUID, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRequestRescheduleTrainingClientResponse(rsp)
}

func (c *ClientWithResponses) RequestRescheduleTrainingWithResponse(ctx context.Context, trainingUUID domain.TrainingUUID, body RequestRescheduleTrainingJSONRequestBody, reqEditors ...RequestEditorFn) (*RequestRescheduleTrainingClientResponse, error) {
	rsp, err := c.RequestRescheduleTraining(ctx, trainingUUID, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRequestRescheduleTrainingClientResponse(rsp)
}

// RescheduleTrainingWithBodyWithResponse request with arbitrary body returning *RescheduleTrainingClientResponse
func (c *ClientWithResponses) RescheduleTrainingWithBodyWithResponse(ctx context.Context, trainingUUID domain.TrainingUUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RescheduleTrainingClientResponse, error) {
	rsp, err := c.RescheduleTrainingWithBody(ctx, trainingUUID, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRescheduleTrainingClientResponse(rsp)
}

func (c *ClientWithResponses) RescheduleTrainingWithResponse(ctx context.Context, trainingUUID domain.TrainingUUID, body RescheduleTrainingJSONRequestBody, reqEditors ...RequestEditorFn) (*RescheduleTrainingClientResponse, error) {
	rsp, err := c.RescheduleTraining(ctx, trainingUUID, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRescheduleTrainingClientResponse(rsp)
}

// ParseGetTrainingsClientResponse parses an HTTP response from a GetTrainingsWithResponse call
func ParseGetTrainingsClientResponse(rsp *http.Response) (*GetTrainingsClientResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetTrainingsClientResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Trainings
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseCreateTrainingClientResponse parses an HTTP response from a CreateTrainingWithResponse call
func ParseCreateTrainingClientResponse(rsp *http.Response) (*CreateTrainingClientResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateTrainingClientResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseCancelTrainingClientResponse parses an HTTP response from a CancelTrainingWithResponse call
func ParseCancelTrainingClientResponse(rsp *http.Response) (*CancelTrainingClientResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CancelTrainingClientResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseApproveRescheduleTrainingClientResponse parses an HTTP response from a ApproveRescheduleTrainingWithResponse call
func ParseApproveRescheduleTrainingClientResponse(rsp *http.Response) (*ApproveRescheduleTrainingClientResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ApproveRescheduleTrainingClientResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseRejectRescheduleTrainingClientResponse parses an HTTP response from a RejectRescheduleTrainingWithResponse call
func ParseRejectRescheduleTrainingClientResponse(rsp *http.Response) (*RejectRescheduleTrainingClientResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RejectRescheduleTrainingClientResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseRequestRescheduleTrainingClientResponse parses an HTTP response from a RequestRescheduleTrainingWithResponse call
func ParseRequestRescheduleTrainingClientResponse(rsp *http.Response) (*RequestRescheduleTrainingClientResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RequestRescheduleTrainingClientResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseRescheduleTrainingClientResponse parses an HTTP response from a RescheduleTrainingWithResponse call
func ParseRescheduleTrainingClientResponse(rsp *http.Response) (*RescheduleTrainingClientResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RescheduleTrainingClientResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}
