// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package http

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"workout/training/domain"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// ErrorDetails defines model for ErrorDetails.
type ErrorDetails struct {
	EntityId   *string `json:"entity_id,omitempty"`
	EntityType *string `json:"entity_type,omitempty"`
	ErrorSlug  string  `json:"error_slug"`
	Message    string  `json:"message"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Details Detailed error information
	Details *[]ErrorDetails `json:"details,omitempty"`

	// Message Human-readable error message
	Message string `json:"message"`

	// Slug Error slug
	Slug string `json:"slug"`
}

// PostTraining defines model for PostTraining.
type PostTraining struct {
	Notes string    `json:"notes"`
	Time  time.Time `json:"time"`
}

// Training defines model for Training.
type Training struct {
	CanBeCancelled     bool                `json:"canBeCancelled"`
	MoveProposedBy     *domain.UserType    `json:"moveProposedBy,omitempty"`
	MoveRequiresAccept bool                `json:"moveRequiresAccept"`
	Notes              string              `json:"notes"`
	ProposedTime       *time.Time          `json:"proposedTime,omitempty"`
	Time               time.Time           `json:"time"`
	User               string              `json:"user"`
	UserUuid           domain.UserUUID     `json:"userUuid"`
	Uuid               domain.TrainingUUID `json:"uuid"`
}

// Trainings defines model for Trainings.
type Trainings struct {
	Trainings []Training `json:"trainings"`
}

// CreateTrainingJSONRequestBody defines body for CreateTraining for application/json ContentType.
type CreateTrainingJSONRequestBody = PostTraining

// RequestRescheduleTrainingJSONRequestBody defines body for RequestRescheduleTraining for application/json ContentType.
type RequestRescheduleTrainingJSONRequestBody = PostTraining

// RescheduleTrainingJSONRequestBody defines body for RescheduleTraining for application/json ContentType.
type RescheduleTrainingJSONRequestBody = PostTraining

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /trainings)
	GetTrainings(ctx echo.Context) error

	// (POST /trainings)
	CreateTraining(ctx echo.Context) error

	// (DELETE /trainings/{trainingUUID})
	CancelTraining(ctx echo.Context, trainingUUID domain.TrainingUUID) error

	// (PUT /trainings/{trainingUUID}/approve-reschedule)
	ApproveRescheduleTraining(ctx echo.Context, trainingUUID domain.TrainingUUID) error

	// (PUT /trainings/{trainingUUID}/reject-reschedule)
	RejectRescheduleTraining(ctx echo.Context, trainingUUID domain.TrainingUUID) error

	// (PUT /trainings/{trainingUUID}/request-reschedule)
	RequestRescheduleTraining(ctx echo.Context, trainingUUID domain.TrainingUUID) error

	// (PUT /trainings/{trainingUUID}/reschedule)
	RescheduleTraining(ctx echo.Context, trainingUUID domain.TrainingUUID) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetTrainings converts echo context to params.
func (w *ServerInterfaceWrapper) GetTrainings(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTrainings(ctx)
	return err
}

// CreateTraining converts echo context to params.
func (w *ServerInterfaceWrapper) CreateTraining(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateTraining(ctx)
	return err
}

// CancelTraining converts echo context to params.
func (w *ServerInterfaceWrapper) CancelTraining(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "trainingUUID" -------------
	var trainingUUID domain.TrainingUUID

	err = runtime.BindStyledParameterWithOptions("simple", "trainingUUID", ctx.Param("trainingUUID"), &trainingUUID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter trainingUUID: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CancelTraining(ctx, trainingUUID)
	return err
}

// ApproveRescheduleTraining converts echo context to params.
func (w *ServerInterfaceWrapper) ApproveRescheduleTraining(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "trainingUUID" -------------
	var trainingUUID domain.TrainingUUID

	err = runtime.BindStyledParameterWithOptions("simple", "trainingUUID", ctx.Param("trainingUUID"), &trainingUUID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter trainingUUID: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApproveRescheduleTraining(ctx, trainingUUID)
	return err
}

// RejectRescheduleTraining converts echo context to params.
func (w *ServerInterfaceWrapper) RejectRescheduleTraining(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "trainingUUID" -------------
	var trainingUUID domain.TrainingUUID

	err = runtime.BindStyledParameterWithOptions("simple", "trainingUUID", ctx.Param("trainingUUID"), &trainingUUID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter trainingUUID: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RejectRescheduleTraining(ctx, trainingUUID)
	return err
}

// RequestRescheduleTraining converts echo context to params.
func (w *ServerInterfaceWrapper) RequestRescheduleTraining(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "trainingUUID" -------------
	var trainingUUID domain.TrainingUUID

	err = runtime.BindStyledParameterWithOptions("simple", "trainingUUID", ctx.Param("trainingUUID"), &trainingUUID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter trainingUUID: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RequestRescheduleTraining(ctx, trainingUUID)
	return err
}

// RescheduleTraining converts echo context to params.
func (w *ServerInterfaceWrapper) RescheduleTraining(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "trainingUUID" -------------
	var trainingUUID domain.TrainingUUID

	err = runtime.BindStyledParameterWithOptions("simple", "trainingUUID", ctx.Param("trainingUUID"), &trainingUUID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter trainingUUID: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RescheduleTraining(ctx, trainingUUID)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/trainings", wrapper.GetTrainings)
	router.POST(baseURL+"/trainings", wrapper.CreateTraining)
	router.DELETE(baseURL+"/trainings/:trainingUUID", wrapper.CancelTraining)
	router.PUT(baseURL+"/trainings/:trainingUUID/approve-reschedule", wrapper.ApproveRescheduleTraining)
	router.PUT(baseURL+"/trainings/:trainingUUID/reject-reschedule", wrapper.RejectRescheduleTraining)
	router.PUT(baseURL+"/trainings/:trainingUUID/request-reschedule", wrapper.RequestRescheduleTraining)
	router.PUT(baseURL+"/trainings/:trainingUUID/reschedule", wrapper.RescheduleTraining)

}

type GetTrainingsRequestObject struct {
}

type GetTrainingsResponseObject interface {
	VisitGetTrainingsResponse(w http.ResponseWriter) error
}

type GetTrainings200JSONResponse Trainings

func (response GetTrainings200JSONResponse) VisitGetTrainingsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetTrainingsdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response GetTrainingsdefaultJSONResponse) VisitGetTrainingsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type CreateTrainingRequestObject struct {
	Body *CreateTrainingJSONRequestBody
}

type CreateTrainingResponseObject interface {
	VisitCreateTrainingResponse(w http.ResponseWriter) error
}

type CreateTraining204Response struct {
}

func (response CreateTraining204Response) VisitCreateTrainingResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type CreateTrainingdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response CreateTrainingdefaultJSONResponse) VisitCreateTrainingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type CancelTrainingRequestObject struct {
	TrainingUUID domain.TrainingUUID `json:"trainingUUID"`
}

type CancelTrainingResponseObject interface {
	VisitCancelTrainingResponse(w http.ResponseWriter) error
}

type CancelTraining204Response struct {
}

func (response CancelTraining204Response) VisitCancelTrainingResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type CancelTrainingdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response CancelTrainingdefaultJSONResponse) VisitCancelTrainingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type ApproveRescheduleTrainingRequestObject struct {
	TrainingUUID domain.TrainingUUID `json:"trainingUUID"`
}

type ApproveRescheduleTrainingResponseObject interface {
	VisitApproveRescheduleTrainingResponse(w http.ResponseWriter) error
}

type ApproveRescheduleTraining204Response struct {
}

func (response ApproveRescheduleTraining204Response) VisitApproveRescheduleTrainingResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type ApproveRescheduleTrainingdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response ApproveRescheduleTrainingdefaultJSONResponse) VisitApproveRescheduleTrainingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type RejectRescheduleTrainingRequestObject struct {
	TrainingUUID domain.TrainingUUID `json:"trainingUUID"`
}

type RejectRescheduleTrainingResponseObject interface {
	VisitRejectRescheduleTrainingResponse(w http.ResponseWriter) error
}

type RejectRescheduleTraining204Response struct {
}

func (response RejectRescheduleTraining204Response) VisitRejectRescheduleTrainingResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RejectRescheduleTrainingdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response RejectRescheduleTrainingdefaultJSONResponse) VisitRejectRescheduleTrainingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type RequestRescheduleTrainingRequestObject struct {
	TrainingUUID domain.TrainingUUID `json:"trainingUUID"`
	Body         *RequestRescheduleTrainingJSONRequestBody
}

type RequestRescheduleTrainingResponseObject interface {
	VisitRequestRescheduleTrainingResponse(w http.ResponseWriter) error
}

type RequestRescheduleTraining204Response struct {
}

func (response RequestRescheduleTraining204Response) VisitRequestRescheduleTrainingResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RequestRescheduleTrainingdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response RequestRescheduleTrainingdefaultJSONResponse) VisitRequestRescheduleTrainingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type RescheduleTrainingRequestObject struct {
	TrainingUUID domain.TrainingUUID `json:"trainingUUID"`
	Body         *RescheduleTrainingJSONRequestBody
}

type RescheduleTrainingResponseObject interface {
	VisitRescheduleTrainingResponse(w http.ResponseWriter) error
}

type RescheduleTraining204Response struct {
}

func (response RescheduleTraining204Response) VisitRescheduleTrainingResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RescheduleTrainingdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response RescheduleTrainingdefaultJSONResponse) VisitRescheduleTrainingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /trainings)
	GetTrainings(ctx context.Context, request GetTrainingsRequestObject) (GetTrainingsResponseObject, error)

	// (POST /trainings)
	CreateTraining(ctx context.Context, request CreateTrainingRequestObject) (CreateTrainingResponseObject, error)

	// (DELETE /trainings/{trainingUUID})
	CancelTraining(ctx context.Context, request CancelTrainingRequestObject) (CancelTrainingResponseObject, error)

	// (PUT /trainings/{trainingUUID}/approve-reschedule)
	ApproveRescheduleTraining(ctx context.Context, request ApproveRescheduleTrainingRequestObject) (ApproveRescheduleTrainingResponseObject, error)

	// (PUT /trainings/{trainingUUID}/reject-reschedule)
	RejectRescheduleTraining(ctx context.Context, request RejectRescheduleTrainingRequestObject) (RejectRescheduleTrainingResponseObject, error)

	// (PUT /trainings/{trainingUUID}/request-reschedule)
	RequestRescheduleTraining(ctx context.Context, request RequestRescheduleTrainingRequestObject) (RequestRescheduleTrainingResponseObject, error)

	// (PUT /trainings/{trainingUUID}/reschedule)
	RescheduleTraining(ctx context.Context, request RescheduleTrainingRequestObject) (RescheduleTrainingResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetTrainings operation middleware
func (sh *strictHandler) GetTrainings(ctx echo.Context) error {
	var request GetTrainingsRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetTrainings(ctx.Request().Context(), request.(GetTrainingsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTrainings")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetTrainingsResponseObject); ok {
		return validResponse.VisitGetTrainingsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateTraining operation middleware
func (sh *strictHandler) CreateTraining(ctx echo.Context) error {
	var request CreateTrainingRequestObject

	var body CreateTrainingJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateTraining(ctx.Request().Context(), request.(CreateTrainingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateTraining")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateTrainingResponseObject); ok {
		return validResponse.VisitCreateTrainingResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CancelTraining operation middleware
func (sh *strictHandler) CancelTraining(ctx echo.Context, trainingUUID domain.TrainingUUID) error {
	var request CancelTrainingRequestObject

	request.TrainingUUID = trainingUUID

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CancelTraining(ctx.Request().Context(), request.(CancelTrainingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CancelTraining")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CancelTrainingResponseObject); ok {
		return validResponse.VisitCancelTrainingResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ApproveRescheduleTraining operation middleware
func (sh *strictHandler) ApproveRescheduleTraining(ctx echo.Context, trainingUUID domain.TrainingUUID) error {
	var request ApproveRescheduleTrainingRequestObject

	request.TrainingUUID = trainingUUID

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ApproveRescheduleTraining(ctx.Request().Context(), request.(ApproveRescheduleTrainingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ApproveRescheduleTraining")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ApproveRescheduleTrainingResponseObject); ok {
		return validResponse.VisitApproveRescheduleTrainingResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// RejectRescheduleTraining operation middleware
func (sh *strictHandler) RejectRescheduleTraining(ctx echo.Context, trainingUUID domain.TrainingUUID) error {
	var request RejectRescheduleTrainingRequestObject

	request.TrainingUUID = trainingUUID

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RejectRescheduleTraining(ctx.Request().Context(), request.(RejectRescheduleTrainingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RejectRescheduleTraining")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(RejectRescheduleTrainingResponseObject); ok {
		return validResponse.VisitRejectRescheduleTrainingResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// RequestRescheduleTraining operation middleware
func (sh *strictHandler) RequestRescheduleTraining(ctx echo.Context, trainingUUID domain.TrainingUUID) error {
	var request RequestRescheduleTrainingRequestObject

	request.TrainingUUID = trainingUUID

	var body RequestRescheduleTrainingJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RequestRescheduleTraining(ctx.Request().Context(), request.(RequestRescheduleTrainingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RequestRescheduleTraining")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(RequestRescheduleTrainingResponseObject); ok {
		return validResponse.VisitRequestRescheduleTrainingResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// RescheduleTraining operation middleware
func (sh *strictHandler) RescheduleTraining(ctx echo.Context, trainingUUID domain.TrainingUUID) error {
	var request RescheduleTrainingRequestObject

	request.TrainingUUID = trainingUUID

	var body RescheduleTrainingJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RescheduleTraining(ctx.Request().Context(), request.(RescheduleTrainingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RescheduleTraining")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(RescheduleTrainingResponseObject); ok {
		return validResponse.VisitRescheduleTrainingResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
